In [2]:
import findspark

In [3]:
findspark.init("/home/xuren/pyspark/spark-2.4.5-bin-hadoop2.7/")

In [4]:
import pyspark

In [5]:
from pyspark.sql import SparkSession, SQLContext

In [5]:
spark = SparkSession.builder.getOrCreate()

In [6]:
spark

In [14]:
from pyspark.sql import Row
from pyspark.sql.types import IntegerType

In [31]:
map(lambda x: Row(value=x), range(10))

In [32]:
list(map(lambda x: Row(value=x), range(10)))

[Row(value=0),
 Row(value=1),
 Row(value=2),
 Row(value=3),
 Row(value=4),
 Row(value=5),
 Row(value=6),
 Row(value=7),
 Row(value=8),
 Row(value=9)]

In [38]:
rdf = spark.createDataFrame(map(lambda x: Row(value=x), range(10)), schema=["col1"], )

In [39]:
rdf.take(2)

[Row(col1=0), Row(col1=1)]

In [40]:
rdf

DataFrame[col1: bigint]

In [46]:
rdd = rdf.rdd.map(tuple)

In [47]:
rdd.collect()

[(0,), (1,), (2,), (3,), (4,), (5,), (6,), (7,), (8,), (9,)]

In [1]:
import numpy as np

In [6]:
np.mean([1,2,4,5,34,1,32,4,34,2,1,3])

10.25

In [7]:
np.median([1,2,4,5,34,1,32,4,34,2,1,3])

3.5

In [8]:
np.std([34,1,23,4,3,3,12,4,3,1])

10.562196741208714

In [9]:
from scipy.stats import kurtosis

In [10]:
kurtosis([34,1,23,4,3,3,12,4,3,1])

0.663124005193275

In [11]:
from scipy.stats import skew

In [12]:
skew([34,1,23,4,3,3,12,4,3,1])

1.4549069329913997

In [13]:
a = [1,2,3,4,5,6,7,8,9,10]
b = [7,6,5,4,5,6,7,8,9,10]

In [14]:
np.correlate(a,b)

array([405])

In [15]:
np.corrcoef(a,b)

array([[1.        , 0.70927291],
       [0.70927291, 1.        ]])

In [16]:
np.cov(a,b)

array([[9.16666667, 4.05555556],
       [4.05555556, 3.56666667]])

In [17]:
np.std(a)

2.8722813232690143

In [18]:
np.std(b)

1.7916472867168918

In [19]:
2.8722813232690143 * 1.7916472867168918

5.146115039522533

In [20]:
5.146115039522533 * 0.70927291

3.649999989276912